const FETCH_NOTES = 'FETCH_NOTES';
const FETCH_SINGLE_NOTE = 'FETCH_SINGLE_NOTE';
const CREATE_NOTE = 'CREATE_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const EDIT_NOTE = 'EDIT_NOTE';

export { FETCH_NOTES, CREATE_NOTE, FETCH_SINGLE_NOTE, DELETE_NOTE, EDIT_NOTE };